[Create] 소셜 로그인 #1
wecode-bootcamp-korea/29-2nd-needed-backend pull request #5
Opened 2022-02-16 10:23 UTC by aerialslash0422

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
소셜 로그인

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 인가 코드 발급
2. 인가 코드 콜백 함수로 액세스 토큰 발급
3. 액세스 토큰으로 유저의 카카오 서버에 담긴 정보 json으로 반환

구현이 너무 길어져서 중간 push 했습니다.
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
콜백과 리다이렉트 , stateless에 대해서 잘 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-02-17 01:31 UTC, bigfanoftim requested changes
우선 기능별로 PR 나눠주시고 리베이스 하셔서 커밋 1개로 줄이신 후 컨플릭트도 해결해주시고 push 해주세요. 지금까지 드린 피드백이 적용된게 하나도 없는 것 같습니다.

2022-02-17 01:51 UTC, aerialslash0422 commented
추가 기능 분리했고 리베이스 완료했습니다.

2022-02-17 02:05 UTC, bigfanoftim requested changes

2022-02-17 02:05 UTC, bigfanoftim commented on users/views.py
> +                    'email': email,
혹시 지금 기획하신 부분 중 같은 카카오 계정에서 이메일이 변경될 경우가 있나요?

2022-02-17 02:05 UTC, bigfanoftim commented on core/utils.py
> +    return response.json()
준영님! kakao 관련 함수들 모아서 class화 한 번 해보시면 좋을 것 같아요. 유닛 테스트 적용 전에 한 번 시도해보세요!

2022-02-17 02:39 UTC, aerialslash0422 commented on users/views.py
> +                    'email': email,
원티드 사이트에서 동의사항에 이메일이 필수로 설정되어 있어도 자체 회원가입 페이지 모달창에서 수정이 가능합니다.
저희가 비즈니스 앱이 아니라서 이메일을 필수 동의사항으로 선택을 못하고 선택사항으로 가져오지만 필수 사항이라고 생각하고 가져온 이메일은 변경 불가로 기획했습니다.

2022-02-17 02:39 UTC, aerialslash0422 commented on core/utils.py
> +    return response.json()
알겠습니다 해보겠습니다.

2022-02-17 05:28 UTC, bigfanoftim requested changes
너무 잘해주셨습니다 준영님! 간단한 리뷰 한 번 확인해보세요~

2022-02-17 05:28 UTC, bigfanoftim commented on core/utils.py
> +        self.user_uri      = 'https://kapi.kakao.com/v2/user/me'
만약 다른 Kakao API를 사용하게 된다면 다른 uri를 또 클래스 attribute에 추가해줘야 합니다. 그럼 어차피 요청하는 uri가 반복된다면 해당 uri만 저장해놓고 메소드만 추가할 수 있게 하면 되지 않을까요?
```suggestion
        self.kakao_api      = 'https://kapi.kakao.com/v2'
        
    def ...(self):
        res = requests.get(
            f"{self.user_url}/...",
            ...
        )
        
    def ...(self):
        res = requests.get(
            f"{self.user_url}/...",
            ...
        )        
        
    def ...(self):
        res = requests.get(
            f"{self.user_url}/...",
            ...
        )
```

2022-02-18 09:52 UTC, bigfanoftim approved these changes
LGTM 👍

2022-02-18 09:52 UTC, merged