[김성수] 이력서 업로드
wecode-bootcamp-korea/29-2nd-needed-backend pull request #6
Opened 2022-02-17 04:32 UTC by shawn365

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
이력서 업로드

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- aws s3 에 파일을 업로드후 db에 파일 url 주소 저장
- 파일이름 중복을 피하기 위해 uuid4 사용

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-02-17 05:35 UTC, bigfanoftim requested changes
현재 PR 기능은 `S3Client` 가 존재해야 작동하는 PR이니 `S3Client` 관련 PR 적용한 후 머지하겠습니다.

2022-02-17 05:35 UTC, bigfanoftim commented on resumes/urls.py
> +    path("/resume", ResumeView.as_view()),
`:8000/resumes/resume`가 의도하신 엔드포인트 주소가 맞나요?
```suggestion
    path("", ResumeView.as_view()),

```

2022-02-17 05:35 UTC, bigfanoftim commented on resumes/views.py
> +from users.utils     import authorization
컨벤션 맞춰주시고, 이전에도 말씀드린 것처럼`my_settings`에 의존하지 않는 다른 방법으로 환경변수를 관리해주세요.

2022-02-17 05:35 UTC, bigfanoftim commented on resumes/views.py
> +            file           = request.FILES.get('document', None)
그냥 file이 아니라 정확한 네이밍 해주세요.
```suggestion
           resume_file           = request.FILES.get('resume', None)
```

2022-02-17 05:35 UTC, bigfanoftim commented on resumes/views.py
> +                user_id  = request.user
```suggestion
                user  = request.user
```

2022-02-18 02:02 UTC, bigfanoftim requested changes
LGTM 👍 
성수님 지금부터는 모든 기능에 해당하는 테스트 코드도 같이 작성해주셔야 합니다. 하지만 테스트 코드 작성이 생각보다 시간이 오래 걸리는 관계로 기존 방식대로 api 기능 만드시면 푸시해주셔서 리뷰 받으시고 이후에 테스트 코드도 더해주고 merge 순서로 진행하시면 되겠습니다~ 가능하시다면 한 번에 올려주셔도 무방합니다.

2022-02-18 04:37 UTC, shawn365 commented
> LGTM 👍 성수님 지금부터는 모든 기능에 해당하는 테스트 코드도 같이 작성해주셔야 합니다. 하지만 테스트 코드 작성이 생각보다 시간이 오래 걸리는 관계로 기존 방식대로 api 기능 만드시면 푸시해주셔서 리뷰 받으시고 이후에 테스트 코드도 더해주고 merge 순서로 진행하시면 되겠습니다~ 가능하시다면 한 번에 올려주셔도 무방합니다.

storagies.py 수정하면서 바뀐부분 있어서 resume도 업데이트 했습니다. aws s3도 test 코드를 만들어야 하나요??

2022-02-22 08:49 UTC, bigfanoftim requested changes
간단한 리뷰입니다~ 바로 적용 후 푸시해주세요!

2022-02-22 08:49 UTC, bigfanoftim commented on resumes/views.py
> +                )
성수님 client 객체는 `Resume` 밖에서 만든 뒤 안에서는 `upload`만 해주시면 좋을 것 같네요~
```suggestion
                s3_client = S3Client(...)
                
                resume = Resume(
                    document = s3_client.upload(resume_file, 'resume/'),
                    user     = request.user             
                )
```

2022-02-23 07:20 UTC, bigfanoftim approved these changes

2022-02-23 07:20 UTC, merged