[김성수] core에 storages.py추가
wecode-bootcamp-korea/29-2nd-needed-backend pull request #8
Opened 2022-02-17 05:10 UTC by shawn365

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
aws 업로드를 도와줄 storages 모듈 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- core 에 storages.py를 만든후 
- 그 안에 aws 업로드를 도와줄 s3client 클래스 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-02-17 05:48 UTC, bigfanoftim requested changes

2022-02-17 05:48 UTC, bigfanoftim commented on core/storages.py
> +            )
하나의 업로드 기능인데 필요한 로직이 밖에 존재합니다. method 안에 넣어주세요.
```suggestion
    def upload(self, file, bucket_name):
        # file_name 만드는 로직 추가
        self.s3.upload_fileobj(
                file,
                bucket_name,
                file_name,
                ExtraArgs={
                    "ContentType": file.content_type
                }
            )           

```

2022-02-17 05:48 UTC, bigfanoftim commented on core/storages.py
> +    def delete(self, file_name, bucket_name):
이 친구도 마찬가지입니다.

2022-02-17 10:40 UTC, shawn365 commented on core/storages.py
> +            )
수정했습니다.

2022-02-17 10:41 UTC, shawn365 commented on core/storages.py
> +    def delete(self, file_name, bucket_name):
수정했습니다.

2022-02-18 01:59 UTC, bigfanoftim requested changes
성수님 수정 너무 잘해주셨는데, `upload`, `delete` 메소드는 `FileHandler` 클래스 내부에 위치하게 하고 s3 client 관리하는 함수는 따로 관리하는게 좋을 것 같네요~  그리고 현재 상황에서 s3 client 함수는 따로 클래스로 분리할 필요는 없어보입니다.

2022-02-18 04:34 UTC, shawn365 commented
> 성수님 수정 너무 잘해주셨는데, `upload`, `delete` 메소드는 `FileHandler` 클래스 내부에 위치하게 하고 s3 client 관리하는 함수는 따로 관리하는게 좋을 것 같네요~ 그리고 현재 상황에서 s3 client 함수는 따로 클래스로 분리할 필요는 없어보입니다.

수정했습니다.

2022-02-18 06:07 UTC, bigfanoftim approved these changes
LGTM 👍

2022-02-18 06:07 UTC, merged